/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sorter_Sorter */

#ifndef _Included_com_sorter_Sorter
#define _Included_com_sorter_Sorter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sorter_Sorter
 * Method:    sort01
 * Signature: ([Ljava/lang/Double;Ljava/lang/Boolean;)[Ljava/lang/Double;
 */
JNIEXPORT jdoubleArray JNICALL Java_com_sorter_Sorter_sort01
  (JNIEnv *, jobject, jdoubleArray, jboolean);

/*
 * Class:     com_sorter_Sorter
 * Method:    sort02
 * Signature: ([Ljava/lang/Double;)[Ljava/lang/Double;
 */
JNIEXPORT jobjectArray JNICALL Java_com_sorter_Sorter_sort02
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     com_sorter_Sorter
 * Method:    sort03
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_sorter_Sorter_sort03
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
